import { StyleSheet } from 'react-native';

const BLUE = '#185FA5';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  backBtn: { width: 32 },
  backIcon: { fontSize: 22, color: '#222222' },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#222222',
    textAlign: 'center',
  },
  content: { padding: 16, paddingBottom: 40 },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: '#EEEEEE' },
  footerRow: {
    flexDirection: 'row',
    padding: 16,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
  },
  label: { fontSize: 14, color: '#555555', marginBottom: 6, marginTop: 8 },
  hint: { fontSize: 12, color: '#888888', marginTop: 4, marginBottom: 8 },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#222222',
    marginBottom: 8,
  },
  primaryBtn: {
    height: 48,
    backgroundColor: BLUE,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  primaryBtnFlex: {
    flex: 1,
    height: 48,
    backgroundColor: BLUE,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineBtn: {
    height: 48,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineBtnFlex: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineBtnText: { color: '#333333', fontSize: 16, fontWeight: '500' },
  hero: {
    backgroundColor: BLUE,
    paddingTop: 24,
    paddingBottom: 24,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  heroTitle: { color: '#FFFFFF', fontSize: 20, fontWeight: '600', marginBottom: 14 },
  searchBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    height: 46,
    paddingHorizontal: 14,
    fontSize: 15,
  },
  listContent: { padding: 16, paddingBottom: 100 },
  examCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E8EE',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    gap: 12,
  },
  tile: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileText: { fontSize: 22 },
  examInfo: { flex: 1 },
  examName: { fontSize: 15, fontWeight: '600', color: '#222222', marginBottom: 2 },
  examMeta: { fontSize: 12, color: '#777777' },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  badgeText: { fontSize: 11, color: '#333333', fontWeight: '500' },
  emptyText: { textAlign: 'center', color: '#888888', fontSize: 14, paddingVertical: 24 },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: BLUE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabText: { color: '#FFFFFF', fontSize: 30, fontWeight: '300', marginTop: -2 },
  card: {
    borderWidth: 1,
    borderColor: '#E5E8EE',
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    marginBottom: 8,
  },
  cardTitle: { fontSize: 15, fontWeight: '600', color: '#222222', marginBottom: 8 },
  optionRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: '#BBBBBB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: BLUE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: BLUE },
  optionLetter: { width: 20, fontSize: 15, fontWeight: '600', color: '#333333' },
  optionInput: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 14,
  },
  examDetailName: { fontSize: 20, fontWeight: '600', color: '#222222', marginBottom: 4 },
  examDetailSub: { fontSize: 13, color: '#777777', marginBottom: 12 },
  detailOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 4,
  },
  detailOptionOk: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 4,
    backgroundColor: '#E6F4EC',
  },
  detailLetter: { width: 22, fontWeight: '600', color: '#555555' },
  detailText: { flex: 1, color: '#333333', fontSize: 14 },
  checkIcon: { fontSize: 16, color: '#1D9E75', fontWeight: '700' },
  dateRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dateInput: {
    flex: 1,
    height: 46,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    textAlign: 'center',
  },
  dateInputYear: {
    flex: 1.5,
    height: 46,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    textAlign: 'center',
  },
  dateSlash: { fontSize: 18, color: '#666666' },
  doneContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  checkCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#1D9E75',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  checkCircleText: { color: '#FFFFFF', fontSize: 36, fontWeight: '700' },
  doneTitle: { fontSize: 20, fontWeight: '600', color: '#222222', marginBottom: 4 },
  doneSub: { fontSize: 14, color: '#777777', marginBottom: 20, textAlign: 'center' },
  linkBox: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    backgroundColor: '#F9FAFB',
  },
  linkText: { fontSize: 13, color: '#333333', textAlign: 'center' },
});
